[tool.poetry]
name = "hurwitzians"
version = "0.1.0"
description = ""
authors = ["James Strudwick <James.Strudwick@ibm.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
